version: '3.6'

services: 
    db:
        image: mysql   
        ports:
          - "3306:3306"     
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: Azure@123
            MYSQL_DATABASE: appdb
            MYSQL_USER: user
            MYSQL_PASSWORD: Azure
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d    